# 配置端口
server:
  port: 8080
  # 配置默认地址
  #servlet:
    #context-path: /xj

spring:
  datasource:
    username: root
    password: Liang123
    url: jdbc:mysql://106.55.48.65:3306/generation_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:com/xj/mapper/xml/*.xml


#mybatis:
  #mapper-locations: classpath:mapping/*Mapper.xml
  #type-aliases-package: com.xj.autogenerationsystem.entity